steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/maraithon/maraithon:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/maraithon/maraithon:latest', '.']

  # Push the container images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/maraithon/maraithon:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/maraithon/maraithon:latest']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/maraithon/maraithon:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/maraithon/maraithon:latest'

options:
  logging: CLOUD_LOGGING_ONLY
