defmodule MaraithonWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :maraithon

  # Companion releases predating byte-budget batching can emit a single
  # realtime Files envelope near 55 MB. CompanionSocket authenticates the
  # device token before WebSock upgrade, so keep this bounded compatibility
  # allowance on that socket only; the public LiveView socket retains
  # Bandit's explicit 8 MB frame and fragmented-message ceilings.
  @legacy_companion_max_frame_bytes 68_000_000

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_maraithon_key",
    signing_salt: "cFALZPAm",
    same_site: "Lax",
    max_age: 60 * 24 * 60 * 60
  ]

  socket "/live", MaraithonWeb.LiveSocket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Realtime ingest channel for the Maraithon Companion macOS app.
  # Authentication happens inside `MaraithonWeb.CompanionSocket.connect/3`
  # via the bearer token supplied as the `"token"` connect param — the
  # same plaintext token clients use against `/api/v1/companion/*`.
  socket "/companion/socket", MaraithonWeb.CompanionSocket,
    websocket: [
      connect_info: [peer_data: true, user_agent: true],
      max_frame_size: @legacy_companion_max_frame_bytes
    ],
    longpoll: false

  # The fixed runtime service has an HTTP listener only for Cloud Run health
  # and exact deployment control. Never expose the browser/API/socket surface
  # through its generated service URL.
  plug MaraithonWeb.Plugs.ProcessRoleGate

  # Reject unsafe HTTP/1 request framing before any endpoint plug can read or
  # drain a body. Telegram authentication remains first within its route gate.
  plug MaraithonWeb.Plugs.TelegramWebhookGate

  # Serve at "/" the static files from "priv/static" directory, including
  # the lightweight PWA shell assets.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # Compiled assets are content-hashed, so they can be cached forever.
  plug Plug.Static,
    at: "/assets",
    from: {:maraithon, "priv/static/assets"},
    gzip: not code_reloading?,
    cache_control_for_etags: "public, max-age=31536000, immutable"

  plug Plug.Static,
    at: "/",
    from: :maraithon,
    gzip: not code_reloading?,
    only: MaraithonWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :maraithon
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    # Independent global/multipart ceiling. The body reader applies stricter
    # route-specific compressed and inflated limits for non-multipart bodies.
    length: 8_388_608,
    body_reader: {MaraithonWeb.Plugs.CacheRawBody, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug MaraithonWeb.Router
end
