defmodule Maraithon.Insights.Insight do
  @moduledoc """
  Persisted actionable insight generated by long-running advisors.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  @statuses ["new", "acknowledged", "dismissed", "snoozed"]
  @categories [
    "reply_urgent",
    "tone_risk",
    "event_important",
    "event_prep_needed",
    "commitment_unresolved",
    "meeting_follow_up",
    "product_opportunity",
    "general"
  ]

  schema "insights" do
    field :user_id, :string
    field :agent_id, :binary_id
    field :source, :string
    field :category, :string
    field :title, :string
    field :summary, :string
    field :recommended_action, :string
    field :priority, :integer, default: 50
    field :confidence, :float, default: 0.5
    field :status, :string, default: "new"
    field :snoozed_until, :utc_datetime_usec
    field :due_at, :utc_datetime_usec
    field :source_id, :string
    field :source_occurred_at, :utc_datetime_usec
    field :dedupe_key, :string
    field :metadata, :map, default: %{}

    timestamps(type: :utc_datetime_usec)
  end

  @required_fields [
    :user_id,
    :agent_id,
    :source,
    :category,
    :title,
    :summary,
    :recommended_action,
    :dedupe_key
  ]

  @optional_fields [
    :priority,
    :confidence,
    :status,
    :snoozed_until,
    :due_at,
    :source_id,
    :source_occurred_at,
    :metadata
  ]

  def changeset(insight, attrs) do
    insight
    |> cast(attrs, @required_fields ++ @optional_fields)
    |> validate_required(@required_fields)
    |> validate_inclusion(:status, @statuses)
    |> validate_inclusion(:category, @categories)
    |> validate_number(:priority, greater_than_or_equal_to: 0, less_than_or_equal_to: 100)
    |> validate_number(:confidence, greater_than_or_equal_to: 0.0, less_than_or_equal_to: 1.0)
    |> validate_length(:title, min: 4, max: 180)
    |> validate_length(:summary, min: 8, max: 1000)
    |> validate_length(:recommended_action, min: 4, max: 500)
    |> validate_length(:dedupe_key, min: 4, max: 255)
    |> unique_constraint(:dedupe_key, name: :insights_user_id_dedupe_key_index)
    |> foreign_key_constraint(:agent_id)
  end
end
